# Generated by Django 5.2.3 on 2025-07-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("overlap_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Input",
            new_name="WorkingHours",
        ),
    ]
