# Generated by Django 5.2.3 on 2025-07-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("overlap_app", "0002_user_workinghours_delete_input"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workinghours",
            name="user",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
